version: '3'
services:
  dbpostgres:
    ports: 
      - "5432:5432"
    container_name: auth_db
    image: "postgres:12.5"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "itsallgood"
      POSTGRES_DB: "postgres"